config/routes.rb
Rails.application.routes.draw do
  root "application#index"
  resources :users
  get 'users/:id/inbox', to: 'users#inbox', as: :inbox
  get 'users/:id/sent_messages', to: 'users#sent_messages', as: :sent_messages
  resources :messages
  get '/messages/:id/content', to: 'messages#content'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  # Validations
  validates :sender_id, presence: true
  validates :recipient_id, presence: true

  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :recipient, class_name: "User", foreign_key: "recipient_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :username, presence: true
  validates :password, presence: true

  has_many :received_messages, class_name: "Message", foreign_key: "recipient_id"
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def index
    if logged_in?
      redirect_to current_user
    else
      @user = User.new
      render erb: 'new'
    end
  end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    if logged_in?
      User.find_by(id:session[:user_id])
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    render layout: false
  end

  def create
    message = Message.new
    recipient = User.find_by(username: params[:recipient_username])
    if !recipient
      @reply = "Cannot send message to #{params[:recipient_username]}. User doesn't exist."
    else
      message.assign_attributes(sender_id: current_user.id, recipient_id: recipient.id, content: params[:content])
      message.save
      @reply = "Successfully sent message to #{params[:recipient_username]}."
    end
  end

  def content
    message = Message.find_by(id: params[:id])
    render plain: message.content
  end

  private

  def message_params
    params.require(:message).permit(:recipient_username, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render partial: 'sessions/login'
  end

  def create
    user = User.find_by(username: params[:username])
    if !user
      flash[:errorlogin] = "User not found."
      redirect_to root_path
    elsif !user.authenticate(params[:password])
      flash[:errorlogin] = "Incorrect password."
      redirect_to root_path
    else
      session[:user_id] = user.id
      redirect_to user
    end
  end

  def destroy
    if session[:user_id]
      session.delete :user_id
    end
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :inbox, :sent_messages]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.valid?
      user.save
      redirect_to user
    else
      flash[:errorusercreate] = "Error creating account."
      redirect_to root_path
    end
  end

  def show
  end

  def inbox
    render json: @user.received_messages
  end

  def sent_messages
    render json: @user.sent_messages
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="header"><span class="title-part-one">Message</span><span class="title-part-two">Box</span></div>
  </div>
  <div class="row justify-content-center">
    <div class="login-form"><%= render "sessions/login" %></div>
  </div>
  <div class="row justify-content-center">
    <h4 class="text-muted"> Join MessageBox community today </h4>
  </div>
  <div class="row justify-content-center">
    <div class="create-account-form">
      <%= render "users/new_user_form" %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/create.js.erb
$("div#mainbox").html("")
$("div#mainbox").html("<%= @reply %>")

app/views/messages/new.html.erb
<%= form_tag("/messages", remote: true) do %>
  <%= text_field_tag :recipient_username, nil, placeholder: "To:", size: 40 %>
  <br>
  <%= text_field_tag :content, nil, placeholder: "Message", size: 40 %>
  <br>
  <%= submit_tag "Send Message" %>
  <br>
<% end %>

app/views/users/_new_user_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.text_field :name, placeholder: "Your Name", size: 40 %>
  <br>
  <%= f.text_field :username, placeholder: "Username", size: 40 %>
  <br>
  <%= f.password_field :password, placeholder: "Password", size: 40 %>
  <br>
  <%= f.submit "Create Account" %>
  <br>
<% end %>

<% if flash[:errorusercreate] %>
  <%= flash[:errorusercreate] %>
<% end %>

app/views/users/new.html.erb
<%= render partial: 'new_user_form'%>

app/views/users/show.html.erb
<div class="header"><span class="title-part-one">Message</span><span class="title-part-two">Box</span></div>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <span class="navbar-brand d-flex flex-fill"> <%= @user.name %> </span>
  <ul class="navbar-nav justify-content-center d-flex flex-fill">
    <li class="nav-item">
      <%= link_to "New Message", new_message_path, class: "nav-link load_new_message" %>
    </li>
    <li class="nav-item">
      <%= link_to "Inbox", inbox_path(@user), class: "nav-link load_inbox" %>
    </li>
    <li class="nav-item">
      <%= link_to "Sent", sent_messages_path(@user), class: "nav-link load_outbox" %>
    </li>
    <li class="nav-item">
      <%= link_to "Logout", "/logout", method: :post, class: "nav-link" %>
    </li>
  </ul>
</nav>


<div id="mainbox" class="container main-box">
</div>